### ISSUE TITLE
compilation error when trying to install on MacOS X

### ISSUE THREAD

**Issue by werschulz** [dunn/homebrew-emacs#751]
Running Mac OS X 10.13.5

Here's the output when i do brew install pdf-tools

``` bash
==> make server/epdfinfo
Last 15 lines from /Users/agw/Library/Logs/Homebrew/pdf-tools/01.make:
clang -DHAVE_CONFIG_H -I.    -w  -g -O2 -MT libsynctex_a-synctex_parser_utils.o -MD -MP -MF .deps/libsynctex_a-synctex_parser_utils.Tpo -c -o libsynctex_a-synctex_parser_utils.o `test -f 'synctex_parser_utils.c' || echo './'`synctex_parser_utils.c
mv -f .deps/libsynctex_a-synctex_parser_utils.Tpo .deps/libsynctex_a-synctex_parser_utils.Po
poppler-hack.cc:88:16: error: cannot initialize a variable of type 'GooString *' with an rvalue of type 'const GooString *'
    GooString *state = a->annot->getAppearState ();
               ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
poppler-hack.cc:108:19: error: assigning to 'GooString *' from incompatible type 'const GooString *'
    text = annot->getDate ();
           ~~~~~~~^~~~~~~~~~
2 errors generated.
make[2]: *** [epdfinfo-poppler-hack.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/libsynctex_a-synctex_parser.Tpo .deps/libsynctex_a-synctex_parser.Po
mv -f .deps/epdfinfo-epdfinfo.Tpo .deps/epdfinfo-epdfinfo.Po
make[1]: *** [all] Error 2
make: *** [server/epdfinfo] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/dunn/homebrew-emacs/issues
```
Thoughts?  Thanks.

**Comment by pmagwene** [comment]
+1 Seeing the same issue on 10.12.6 w/latest homebrew.

**Comment by dunn** [comment]
And looks like that in turn is related to https://github.com/politza/pdf-tools/issues/372.

Not a lot we can do on our end until the bug is patched.

**Comment by fshapps** [comment]
Looks like politza/pdf-tools#389 and politza/pdf-tools#372 have both been marked resolved. I just tried to install pdf-tools via brew and am getting the same error message reported earlier. Is there still an issue w/ the pdf-tools code or has brew not been updated yet?

**Comment by dunn** [comment]
There hasn't been a new release of pdf-tools since those were resolved.  Until there is, you can install the master branch with `brew install --HEAD pdf-tools`.

**Comment by Nathanael8** [comment]
It seems like this is still an issue, since I got the same error when I tried to install pdf-tools.

```
 make server/epdfinfo CC=/usr/bin/gcc CXX=/usr/bin/gcc AR=/usr/bin/ar RANLIB=
Last 15 lines from /Users/nathanaelskrepek/Library/Logs/Homebrew/pdf-tools/01.make:
                          ~  ^
poppler-hack.cc:88:16: error: cannot initialize a variable of type 'GooString *' with an rvalue of type 'const GooString *'
    GooString *state = a->annot->getAppearState ();
               ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
poppler-hack.cc:108:19: error: assigning to 'GooString *' from incompatible type 'const GooString *'
    text = annot->getDate ();
           ~~~~~~~^~~~~~~~~~
3 errors generated.
make[2]: *** [epdfinfo-poppler-hack.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 warning generated.
mv -f .deps/epdfinfo-epdfinfo.Tpo .deps/epdfinfo-epdfinfo.Po
mv -f .deps/libsynctex_a-synctex_parser.Tpo .deps/libsynctex_a-synctex_parser.Po
make[1]: *** [all] Error 2
make: *** [server/epdfinfo] Error 2
```

`brew install --HEAD pdf-tools` didn't cause an error.
